// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBASJq7AnTWp9iCzh2p90iKXf4ISSXn19c',
    appId: '1:918125090227:web:c9790b24e746df46a867c6',
    messagingSenderId: '918125090227',
    projectId: 'social-app-6b992',
    authDomain: 'social-app-6b992.firebaseapp.com',
    storageBucket: 'social-app-6b992.appspot.com',
    measurementId: 'G-N06Q37F6S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxarVBwWPwtMLaL8EkWQlstjVSsszYpt0',
    appId: '1:918125090227:android:257e65eb6515f80ca867c6',
    messagingSenderId: '918125090227',
    projectId: 'social-app-6b992',
    storageBucket: 'social-app-6b992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASm8dW-Tg2Ui0M8WNA-jn8rsQSACV1V50',
    appId: '1:918125090227:ios:0081d08aa7accf53a867c6',
    messagingSenderId: '918125090227',
    projectId: 'social-app-6b992',
    storageBucket: 'social-app-6b992.appspot.com',
    iosClientId: '918125090227-53pmc56ckmk1q6as63h6dacj4s05hbs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASm8dW-Tg2Ui0M8WNA-jn8rsQSACV1V50',
    appId: '1:918125090227:ios:0081d08aa7accf53a867c6',
    messagingSenderId: '918125090227',
    projectId: 'social-app-6b992',
    storageBucket: 'social-app-6b992.appspot.com',
    iosClientId: '918125090227-53pmc56ckmk1q6as63h6dacj4s05hbs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
